
homeassistant:
  external_url: "https://home.jassie.us"
  internal_url: "http://192.168.4.58:8123"
# Loads default set of integrations. Do not remove.
default_config:

input_text:
  petlibro_email:
    name: Petlibro email
    initial: !secret petlibro_email
    mode: password
    max: 128
  petlibro_password:
    name: Petlibro password
    initial: !secret petlibro_password
    mode: password
    max: 128
  petlibro_wet_food_device_sn:
    name: Petlibro wet food feeder serial
    initial: !secret petlibro_wet_food_device_sn
    mode: password
    max: 32

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

lovelace:
  dashboards:
    front-yard-view:
      mode: yaml
      title: Front Yard
      icon: mdi:grass
      show_in_sidebar: false
      filename: dashboards/front-yard.yaml
    map-view:
      mode: yaml
      title: Map
      icon: mdi:map
      show_in_sidebar: true
      filename: dashboards/map.yaml
    energy-view:
      mode: yaml
      title: Energy
      icon: mdi:lightning-bolt
      show_in_sidebar: true
      filename: dashboards/energy.yaml

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include templates.yaml

google_assistant:
  project_id: he-voice-06a10
  service_account: !include SERVICE_ACCOUNT.JSON
  report_state: true
  expose_by_default: true

rest_command:
  sweepy_webhook:
    url: "https://sweepy.jassie.us/api/ha-webhook"
    method: POST
    headers:
      x-webhook-secret: "{{ secret }}"
    content_type: "application/json"
    payload: '{"action": "{{ action }}"}'
  petlibro_login:
    url: "https://api.us.petlibro.com/member/auth/login"
    method: POST
    headers:
      source: "ANDROID"
      language: "EN"
      timezone: "America/Chicago"
      version: "1.3.45"
      Content-Type: "application/json"
    payload: >-
      {"appId":1,"appSn":"c35772530d1041699c87fe62348507a8","country":"US","email":"{{ states('input_text.petlibro_email') }}","password":"{{ states('input_text.petlibro_password') | md5 }}","phoneBrand":"","phoneSystemVersion":"","timezone":"America/Chicago","thirdId":null,"type":null}
  petlibro_cleaning_reset:
    url: "https://api.us.petlibro.com/device/device/machineCleaningReset"
    method: POST
    headers:
      token: "{{ token }}"
      source: "ANDROID"
      language: "EN"
      timezone: "America/Chicago"
      version: "1.3.45"
      Content-Type: "application/json"
    payload: >-
      {"deviceSn":"{{ device_sn }}","requestId":"{{ request_id }}","timeout":5000}

logger:
  default: warning
  logs:
    custom_components.petlibro: debug
